In [2]:
# Dependencies
import pandas as pd
import numpy as np 
import pymongo
import datetime as dt
import matplotlib.pyplot as plt

In [3]:
# pd.set_option('display.height', 100)
# pd.set_option('display.max_rows', 85)
# pd.set_option('display.max_columns', 100)
# pd.set_option('display.width', 100)

In [4]:
# Load data 
train_data_csv = ('Resources/train.csv')

In [5]:
train_data_df = pd.read_csv(train_data_csv)
train_data_df.tail(25)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
1435,1436,20,RL,80.0,8400,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,NaN,0,7,2008,COD,Abnorml,174000
1436,1437,20,RL,60.0,9000,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdWo,NaN,0,5,2007,WD,Normal,120500
1437,1438,20,RL,96.0,12444,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,11,2008,New,Partial,394617
1438,1439,20,RM,90.0,7407,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,4,2010,WD,Normal,149700
1439,1440,60,RL,80.0,11584,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,11,2007,WD,Normal,197000
1440,1441,70,RL,79.0,11526,Pave,NaN,IR1,Bnk,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,191000
1441,1442,120,RM,NaN,4426,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2008,WD,Normal,149300
1442,1443,60,FV,85.0,11003,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2009,WD,Normal,310000
1443,1444,30,RL,NaN,8854,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2009,WD,Normal,121000
1444,1445,20,RL,63.0,8500,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,11,2007,WD,Normal,179600
1445,1446,85,RL,70.0,8400,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,129000
1446,1447,20,RL,NaN,26142,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,157900
1447,1448,60,RL,80.0,10000,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2007,WD,Normal,240000
1448,1449,50,RL,70.0,11767,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdWo,NaN,0,5,2007,WD,Normal,112000
1449,1450,180,RM,21.0,1533,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2006,WD,Abnorml,92000
1450,1451,90,RL,60.0,9000,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2009,WD,Normal,136000
1451,1452,20,RL,78.0,9262,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2009,New,Partial,287090
1452,1453,180,RM,35.0,3675,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2006,WD,Normal,145000
1453,1454,20,RL,90.0,17217,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,7,2006,WD,Abnorml,84500
1454,1455,20,FV,62.0,7500,Pave,Pave,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,10,2009,WD,Normal,185000
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

In [6]:
train_data_df.columns

Index(['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig',
       'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType',
       'HouseStyle', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd',
       'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType',
       'MasVnrArea', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual',
       'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1',
       'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating',
       'HeatingQC', 'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual',
       'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType',
       'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual',
       'GarageCond', 'PavedDrive', 'WoodDeckSF', 'OpenPorchSF',
       'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'PoolQC',
       'Fence', 'MiscFeature', 'MiscVal', 'MoSold', 'YrSold', 'SaleType',
       'SaleCondition', 'SalePrice'],
      dtype='object')

In [7]:
#Examine Missing Data

train_data_df.isnull()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,False,False,False,False,False,False,True,False,False,False,...,False,True,True,True,False,False,False,False,False,False
1,False,False,False,False,False,False,True,False,False,False,...,False,True,True,True,False,False,False,False,False,False
2,False,False,False,False,False,False,True,False,False,False,...,False,True,True,True,False,False,False,False,False,False
3,False,False,False,False,False,False,True,False,False,False,...,False,True,True,True,False,False,False,False,False,False
4,False,False,False,False,False,False,True,False,False,False,...,False,True,True,True,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,False,False,False,False,False,False,True,False,False,False,...,False,True,True,True,False,False,False,False,False,False
1456,False,False,False,False,False,False,True,False,False,False,...,False,True,False,True,False,False,False,False,False,False
1457,False,False,False,False,False,False,True,False,False,False,...,False,True,False,False,False,False,False,False,False,False
1458,False,False,False,False,False,False,True,False,False,False,...,False,True,True,True,False,False,False,False,False,False
1459,False,False,False,False,False,False,True,False,False,False,...,False,True,True,True,False,False,False,False,False,False

In [8]:
# Count NaN values in columns
train_data_df.isnull().sum()

Id                 0
MSSubClass         0
MSZoning           0
LotFrontage      259
LotArea            0
                ...
MoSold             0
YrSold             0
SaleType           0
SaleCondition      0
SalePrice          0
Length: 81, dtype: int64

In [9]:
#Refer to Kaggle train data description for approriate values to
# to replace NaN values


train_data_df['LotFrontage'].fillna("0",inplace = True)
train_data_df['Alley'].fillna("None",inplace = True)
train_data_df['MSZoning'].fillna("None",inplace = True)
train_data_df['MasVnrType'].fillna("None",inplace = True)
train_data_df['MasVnrArea'].fillna("0",inplace = True)
train_data_df['BsmtQual'].fillna("NA",inplace = True)
train_data_df['BsmtCond'].fillna("NA",inplace = True)
train_data_df['BsmtExposure'].fillna("NA",inplace = True)
train_data_df['BsmtFinType1'].fillna("NA",inplace = True)
train_data_df['BsmtFinType2'].fillna("NA",inplace = True)
train_data_df['Electrical'].fillna("None",inplace = True)
train_data_df['FireplaceQu'].fillna("NO",inplace = True)
train_data_df['GarageType'].fillna("NA",inplace = True)
train_data_df['GarageYrBlt'].fillna("0",inplace = True)
train_data_df['GarageFinish'].fillna("NA",inplace = True)
train_data_df['GarageQual'].fillna("NA",inplace = True)
train_data_df['GarageCond'].fillna("NA",inplace = True)
train_data_df['PoolQC'].fillna("NA",inplace = True)
train_data_df['Fence'].fillna("NO",inplace = True)
train_data_df['MiscFeature'].fillna("NA",inplace = True)

In [10]:
train_data_df.isnull().sum()

Id               0
MSSubClass       0
MSZoning         0
LotFrontage      0
LotArea          0
                ..
MoSold           0
YrSold           0
SaleType         0
SaleCondition    0
SalePrice        0
Length: 81, dtype: int64

In [16]:
#Create a total Sqft Column buy adding 1st,2nd, 
#basement if finished

#did not include lot Area, but can
train_data_df['TotalSQFT']= train_data_df['GrLivArea']+ train_data_df['BsmtFinSF2']+ train_data_df['BsmtFinSF1']
train_data_df['TotalSQFT']

0       2416
1       2240
2       2272
3       1933
4       2853
        ...
1455    1647
1456    3026
1457    2615
1458    2156
1459    2376
Name: TotalSQFT, Length: 1460, dtype: int64

In [17]:
#Create a Price Per Square Foot Column
#Dividing the sales price by total square footage include living space size
train_data_df['PPsQFT']=train_data_df['SalePrice']/train_data_df['TotalSQFT']

train_data_df['PPsQFT']

0        86.299669
1        81.026786
2        98.371479
3        72.426280
4        87.627059
           ...
1455    106.253795
1456     69.398546
1457    101.912046
1458     65.920686
1459     62.079125
Name: PPsQFT, Length: 1460, dtype: float64

In [20]:
#Create a Price Per LotColumn
#Dividing the sales price by total square footage include lot size
train_data_df['PPLot']=train_data_df['SalePrice']/train_data_df['LotArea']

train_data_df['PPLot']

0       24.674556
1       18.906250
2       19.866667
3       14.659686
4       17.531557
          ...
1455    22.104332
1456    15.939279
1457    29.473568
1458    14.626428
1459    14.843514
Name: PPLot, Length: 1460, dtype: float64

In [21]:
train_data_df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice,TotalSQFT,PPsQFT,PPLot
0,1,60,RL,65,8450,Pave,None,Reg,Lvl,AllPub,...,NA,0,2,2008,WD,Normal,208500,2416,86.299669,24.674556
1,2,20,RL,80,9600,Pave,None,Reg,Lvl,AllPub,...,NA,0,5,2007,WD,Normal,181500,2240,81.026786,18.906250
2,3,60,RL,68,11250,Pave,None,IR1,Lvl,AllPub,...,NA,0,9,2008,WD,Normal,223500,2272,98.371479,19.866667
3,4,70,RL,60,9550,Pave,None,IR1,Lvl,AllPub,...,NA,0,2,2006,WD,Abnorml,140000,1933,72.426280,14.659686
4,5,60,RL,84,14260,Pave,None,IR1,Lvl,AllPub,...,NA,0,12,2008,WD,Normal,250000,2853,87.627059,17.531557

In [22]:
train_export=train_data_df.to_csv('Resources/CleanTrainData.csv',index=False)